version: '3.4'

services:
  gateway.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  car.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"

  company.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5020:80"


  user.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5030:80"

